name: tractians_mobile_challenge
description: "a tractician mobile challenge"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  content_repository:
    path: packages/content_repository

  company_repository:
    path: packages/company_repository    
    
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/apidata.json
    - assets/images/